https://github.com/fadhiilahahmadzikri/sanctrum-voice-v2# -*- coding: utf-8 -*-
"""Proyek TPDB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJh89JSQHh1yKzzywe6cW9roKZIUEYwD
"""

from google.colab import files

uploaded = files.upload()

from google.colab import files

uploaded = files.upload()

import pandas as pd

df_poi = pd.read_csv('Common_Points_of_Interest.csv')

df_parks = df_poi[df_poi['NAME'].str.contains('Park', case=False, na=False)]

df_hospitals = df_poi[df_poi['NAME'].str.contains('Hospital|Medical Center', case=False, na=False)]

df_schools = df_poi[df_poi['NAME'].str.contains('School', case=False, na=False)]

df_security = df_poi[df_poi['NAME'].str.contains('Police|Sheriff|Fire', case=False, na=False)]

print(f"Jumlah Taman: {len(df_parks)}")
print(f"Jumlah Rumah Sakit: {len(df_hospitals)}")
print(f"Jumlah Sekolah: {len(df_schools)}")

df_parks.head()

!pip install pyproj

from pyproj import Transformer

transformer = Transformer.from_crs("EPSG:2285", "EPSG:4326", always_xy=True)

def convert_coords(df):
    lon, lat = transformer.transform(df['x'].values, df['y'].values)
    df['lat'] = lat
    df['lon'] = lon
    return df

df_parks = convert_coords(df_parks.copy())
df_hospitals = convert_coords(df_hospitals.copy())
df_schools = convert_coords(df_schools.copy())

print(df_parks[['NAME', 'lat', 'lon']].head())

# Cek jumlah data yang berhasil dipisahkan
print(f"Jumlah Taman: {len(df_parks)}")
print(f"Jumlah Rumah Sakit: {len(df_hospitals)}")
print(f"Jumlah Sekolah: {len(df_schools)}")

# Menampilkan 5 data pertama dari kategori taman
df_parks.head()

df_rumah = pd.read_csv('kc_house_data.csv')
display(df_rumah.head())

# Ganti nama di dalam kurung sesuai hasil df_rumah.columns tadi
# Misal: 'SalePrice' bukan 'price'
try:
    # Coba tampilkan dengan nama kolom yang umum di dataset King County
    print(df_rumah[['SalePrice', 'lat', 'long']].head())
except KeyError:
    # Jika masih error, tampilkan semua kolom agar kita bisa cek manual
    print("Kolom tidak ditemukan. Berikut daftar kolom yang ada:")
    print(df_rumah.columns)

df_poi_all = convert_coords(df_poi.copy())

zip_coords = df_poi_all.groupby('ZIPCODE')[['lat', 'lon']].mean().reset_index()

df_rumah['ZipCode'] = df_rumah['ZipCode'].astype(int)
zip_coords['ZIPCODE'] = zip_coords['ZIPCODE'].astype(int)

df_rumah = pd.merge(df_rumah, zip_coords, left_on='ZipCode', right_on='ZIPCODE', how='left')

print(df_rumah[['SalePrice', 'ZipCode', 'lat', 'lon']].head())

df_rumah = df_rumah.dropna(subset=['lat', 'lon'])
print(f"Sisa data setelah pembersihan: {len(df_rumah)}")

from scipy.spatial import cKDTree
import numpy as np

def hitung_jarak_terdekat(df_target, df_fasilitas, nama_kolom):
    tree = cKDTree(df_fasilitas[['lat', 'lon']].values)
    dist, _ = tree.query(df_target[['lat', 'lon']].values, k=1)

    df_target[nama_kolom] = dist * 111
    return df_target

df_rumah = hitung_jarak_terdekat(df_rumah, df_parks, 'dist_to_park')
df_rumah = hitung_jarak_terdekat(df_rumah, df_schools, 'dist_to_school')
df_rumah = hitung_jarak_terdekat(df_rumah, df_hospitals, 'dist_to_hospital')

print("Hasil Feature Engineering (Jarak Fasilitas):")
print(df_rumah[['SalePrice', 'dist_to_park', 'dist_to_school', 'dist_to_hospital']].head())

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
features = [
    'SqFtTotLiving', 'Bedrooms', 'Bathrooms', 'BldgGrade',
    'dist_to_park', 'dist_to_school', 'dist_to_hospital'
]

df_model = df_rumah.dropna(subset=features + ['SalePrice'])

X = df_model[features]
y = df_model['SalePrice']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

model_baseline = LinearRegression()
model_baseline.fit(X_train, y_train)

y_pred_baseline = model_baseline.predict(X_test)
r2_baseline = r2_score(y_test, y_pred_baseline)

print(f"R-Squared Model Baseline (Iterasi 1): {r2_baseline:.4f}")

# Inisialisasi dan melatih model
model = LinearRegression()
model.fit(X_train, y_train)

# Melakukan prediksi pada data uji
y_pred = model.predict(X_test)

# Menghitung Metrik Evaluasi
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"R-Squared (Akurasi Model): {r2:.4f}")
print(f"Rata-rata Kesalahan Prediksi (MAE): ${mae:,.2f}")

# Melihat pengaruh masing-masing fitur (Koefisien)
coefficients = pd.DataFrame({'Feature': features, 'Coefficient': model.coef_})
print("\nPengaruh Fitur terhadap Harga:")
print(coefficients.sort_values(by='Coefficient', ascending=False))

import matplotlib.pyplot as plt
import seaborn as sns

# Mengurutkan koefisien
coefficients = coefficients.sort_values(by='Coefficient')

plt.figure(figsize=(10, 6))
sns.barplot(x='Coefficient', y='Feature', data=coefficients, palette='viridis')
plt.title('Pengaruh Fitur terhadap Harga Rumah (Koefisien Regresi)')
plt.xlabel('Nilai Koefisien')
plt.ylabel('Fitur')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()

df_rumah['HouseAge'] = 2026 - df_rumah['YrBuilt']
# Tambahkan 'HouseAge' ke dalam daftar features kamu

import numpy as np
y = np.log(df_model['SalePrice'])

df_rumah['Space_Quality'] = df_rumah['SqFtTotLiving'] * df_rumah['BldgGrade']

import numpy as np

y_log = np.log(df_model['SalePrice'])
X = df_model[features]

X_train, X_test, y_train_log, y_test_log = train_test_split(X, y_log, test_size=0.2, random_state=42)

model_log = LinearRegression()
model_log.fit(X_train, y_train_log)

y_pred_log = model_log.predict(X_test)

r2_baru = r2_score(y_test_log, y_pred_log)
print(f"R-Squared Baru (Setelah Log Transformation): {r2_baru:.4f}")

# Mengembalikan hasil prediksi ke harga asli
y_pred_asli = np.exp(y_pred_log)
y_test_asli = np.exp(y_test_log)

# Hitung MAE dalam satuan harga asli
mae_asli = mean_absolute_error(y_test_asli, y_pred_asli)
print(f"Rata-rata Kesalahan Prediksi Asli: ${mae_asli:,.2f}")

# Ambil koefisien dari model yang sudah di-Log
log_coefficients = pd.DataFrame({'Feature': features, 'Coefficient': model_log.coef_})
log_coefficients = log_coefficients.sort_values(by='Coefficient')

plt.figure(figsize=(10, 6))
sns.barplot(x='Coefficient', y='Feature', data=log_coefficients, palette='magma')
plt.title('Pengaruh Fitur terhadap Log Harga Rumah (Model Optimasi)')
plt.xlabel('Nilai Koefisien (Persentase Pengaruh)')
plt.ylabel('Fitur')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()

# Karena data ini dari tahun 2014-2015, kita gunakan 2015 sebagai patokan
df_model['HouseAge'] = 2015 - df_model['YrBuilt']

# Menghapus rumah dengan harga yang sangat ekstrim
q_low = df_model["SalePrice"].quantile(0.01)
q_hi  = df_model["SalePrice"].quantile(0.99)
df_model = df_model[(df_model["SalePrice"] < q_hi) & (df_model["SalePrice"] > q_low)]

df_final = pd.get_dummies(df_model, columns=['ZipCode'], drop_first=True)

# Menentukan target dan fitur
# Kita gunakan df_final karena itu yang sudah di-dummies
target = 'SalePrice'

# Ambil semua kolom kecuali target dan kolom non-numerik lainnya
features_final = [col for col in df_final.columns if col not in [target, 'DocumentDate', 'PropertyID', 'PropertyType', 'ym', 'YrBuilt']]

X = df_final[features_final]
# Gunakan log transformation lagi karena tadi terbukti sangat ampuh
y = np.log(df_final[target])

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model_final = LinearRegression()
model_final.fit(X_train, y_train)

y_pred = model_final.predict(X_test)
r2_final = r2_score(y_test, y_pred)

print(f"R-Squared Final: {r2_final:.4f}")

# Melihat 10 fitur paling berpengaruh
coef_df = pd.DataFrame({'Feature': features_final, 'Coef': model_final.coef_})
print(coef_df.sort_values(by='Coef', ascending=False).head(10))

import matplotlib.pyplot as plt
import seaborn as sns

# Mengembalikan nilai log ke harga asli untuk visualisasi yang lebih jelas
y_test_asli = np.exp(y_test)
y_pred_asli = np.exp(y_pred)

plt.figure(figsize=(10, 6))
sns.regplot(x=y_test_asli, y=y_pred_asli, scatter_kws={'alpha':0.3}, line_kws={'color':'red'})
plt.title('Akurasi Model Final: Harga Aktual vs Harga Prediksi')
plt.xlabel('Harga Aktual ($)')
plt.ylabel('Harga Prediksi ($)')
plt.show()

# Mengambil koefisien dari model final
coef_final = pd.DataFrame({'Feature': features_final, 'Coefficient': model_final.coef_})
coef_final = coef_final.sort_values(by='Coefficient', ascending=False)

# Ambil 10 teratas dan 10 terbawah
top_bottom_coef = pd.concat([coef_final.head(10), coef_final.tail(10)])

plt.figure(figsize=(12, 8))
sns.barplot(x='Coefficient', y='Feature', data=top_bottom_coef, palette='coolwarm')
plt.title('10 Fitur Peningkat Harga vs 10 Fitur Penurun Harga Terkuat', fontsize=14)
plt.xlabel('Nilai Koefisien (Persentase Pengaruh dalam Skala Log)')
plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# --- DIAGRAM 1: PROGRESS AKURASI ---
models = ['Model Awal', 'Model + Log', 'Model Final (Optimasi)']
r_squared_values = [0.5685, 0.6850, 0.9457]

plt.figure(figsize=(10, 6))
bars = plt.bar(models, r_squared_values, color=['#d1d1d1', '#a2c4c9', '#4e79a7'])

# Tambahkan angka di atas bar
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.01, f'{yval:.4f}', ha='center', va='bottom', fontweight='bold')

plt.ylim(0, 1.1)
plt.title('Peningkatan Akurasi Model (R-Squared)', fontsize=14)
plt.ylabel('R-Squared Score')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.savefig('progres_akurasi.png')
plt.show()

# --- DIAGRAM 2: ACTUAL VS PREDICTED ---
# (Gunakan y_test dan y_pred asli kamu dari cell sebelumnya)
y_test_asli = np.exp(y_test)
y_pred_asli = np.exp(y_pred)

plt.figure(figsize=(10, 6))
plt.scatter(y_test_asli, y_pred_asli, alpha=0.4, color='teal', label='Titik Data')
plt.plot([y_test_asli.min(), y_test_asli.max()], [y_test_asli.min(), y_test_asli.max()],
         color='red', linestyle='--', lw=2, label='Garis Prediksi Sempurna')

plt.title('Akurasi Model Final (Actual vs Predicted)', fontsize=14)
plt.xlabel('Harga Rumah Aktual ($)')
plt.ylabel('Harga Rumah Prediksi ($)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig('actual_vs_predicted.png')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Kita paksa logaritma ulang agar grafiknya benar-benar skala Log
y_test_log_plot = np.log(y_test_asli)
y_pred_log_plot = np.log(y_pred_asli)

plt.figure(figsize=(10, 6))
sns.regplot(x=y_test_log_plot, y=y_pred_log_plot,
            scatter_kws={'alpha':0.4, 'color':'teal'},
            line_kws={'color':'red', 'ls':'--'})

plt.title('Akurasi Model Final (Skala Logaritma)', fontsize=14)
plt.xlabel('Log Harga Aktual')
plt.ylabel('Log Harga Prediksi')
plt.grid(True, alpha=0.3)
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_test_asli, y=y_pred_asli, alpha=0.4, color='teal', label='Titik Data')

# Buat garis merah ideal
plt.plot([0, 1500000], [0, 1500000], color='red', linestyle='--', lw=2, label='Garis Prediksi Sempurna')

# TRIK ZOOM IN: Kita batasi sumbu X dan Y maksimum di angka $1.5 Juta
plt.xlim(100000, 1500000)
plt.ylim(100000, 1500000)

plt.title('Akurasi Model Final untuk Properti < $1.5 Juta', fontsize=14)
plt.xlabel('Harga Rumah Aktual ($)')
plt.ylabel('Harga Rumah Prediksi ($)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

threshold = np.median(y_test_asli)

y_test_binary = (y_test_asli > threshold).astype(int)
y_pred_binary = (y_pred_asli > threshold).astype(int)

cm = confusion_matrix(y_test_binary, y_pred_binary)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Dibawah Median (0)', 'Diatas Median (1)'],
            yticklabels=['Dibawah Median (0)', 'Diatas Median (1)'])

plt.title('Confusion Matrix: Validasi Segmentasi Harga Properti', fontsize=14)
plt.xlabel('Predicted Label (Tebakan AI)')
plt.ylabel('True Label (Data Aktual)')
plt.show()

print("\nLaporan Performa Klasifikasi (Binary Segmentation):")
print(classification_report(y_test_binary, y_pred_binary))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error
test_sizes = [0.10, 0.20, 0.25, 0.30]
rasio_labels = ['90:10', '80:20', '75:25', '70:30']

hasil_eksperimen = []
for ts, label in zip(test_sizes, rasio_labels):
    X_train_eks, X_test_eks, y_train_eks, y_test_eks = train_test_split(X, y, test_size=ts, random_state=42)
    model_eks = LinearRegression()
    model_eks.fit(X_train_eks, y_train_eks)
    y_pred_eks = model_eks.predict(X_test_eks)
    skor_r2 = r2_score(y_test_eks, y_pred_eks)
    mae_asli = mean_absolute_error(np.exp(y_test_eks), np.exp(y_pred_eks))
    hasil_eksperimen.append({
        'Rasio Train:Test': label,
        'R-Squared': skor_r2,
        'MAE ($)': mae_asli
    })
df_hasil = pd.DataFrame(hasil_eksperimen)
print("=== TABEL PERBANDINGAN RASIO PEMBAGIAN DATA ===")
display(df_hasil)
plt.figure(figsize=(10, 5))
sns.lineplot(data=df_hasil, x='Rasio Train:Test', y='R-Squared', marker='o', color='b', linewidth=2, markersize=8)
plt.title('Analisis Sensitivitas: Pengaruh Rasio Data Latih terhadap R-Squared', fontsize=14)
plt.xlabel('Rasio Pembagian Data (Train : Test)', fontsize=12)
plt.ylabel('Skor R-Squared', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
plt.ylim(0.90, 0.96)
plt.show()

from google.colab import files
df_final.to_csv('dataset_properti_final_skripsi.csv', index=False)

print("File berhasil disimpan di memori Colab. Memulai proses unduhan...")

files.download('dataset_properti_final_skripsi.csv')

import joblib
from google.colab import files

# 1. Simpan model regresi linear final
joblib.dump(model_final, 'model_harga_properti.pkl')

# 2. Simpan daftar urutan kolom fitur final (termasuk dummy ZipCode)
joblib.dump(features_final, 'daftar_fitur.pkl')

# 3. Unduh kedua file tersebut ke laptop
files.download('model_harga_properti.pkl')
files.download('daftar_fitur.pkl')